# Generated by Django 4.2.3 on 2023-07-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0002_companiesprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(default=True, verbose_name='is_company'),
        ),
    ]
