# Generated by Django 4.2.3 on 2023-07-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0004_addemploye'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddEmploye',
            new_name='Employe',
        ),
    ]
