# Generated by Django 4.2.3 on 2023-07-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0005_rename_addemploye_employe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employe',
            new_name='Employee',
        ),
    ]
