# Generated by Django 4.2.3 on 2023-07-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0006_rename_employe_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default='tgg', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='8765768', max_length=15, unique=True),
        ),
    ]
