# Generated by Django 4.2.3 on 2023-07-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0013_alter_provideddevice_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provideddevice',
            old_name='checkeout_date',
            new_name='checkout_date',
        ),
    ]
