# Generated by Django 4.2.3 on 2023-07-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0014_rename_checkeout_date_provideddevice_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesprofile',
            name='image',
            field=models.ImageField(default='no_profile.png', upload_to='profilepicture'),
        ),
    ]
